# Generated by Django 2.0.5 on 2018-05-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('isBomb', models.BooleanField(default=False)),
                ('isOpen', models.BooleanField(default=False)),
                ('isFlagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('PRO', 'Professional')], default='BEG', max_length=12)),
                ('bombsLeft', models.IntegerField()),
                ('elapsedTime', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='gameSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GameSession'),
        ),
    ]
