# Generated by Django 2.0.5 on 2018-05-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='bombsLeft',
            new_name='flagsLeft',
        ),
    ]
