# Generated by Django 2.0.5 on 2018-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180510_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='isOver',
            field=models.BooleanField(default=False),
        ),
    ]
