# Generated by Django 2.0.5 on 2018-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_gamesession_isover'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='countOpen',
            field=models.IntegerField(default=0),
        ),
    ]
