# Generated by Django 2.0.5 on 2018-05-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_gamesession_countopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='bigOpen',
            field=models.BooleanField(default=False),
        ),
    ]
